-- Ejemplo de registro para app_themes.
-- No modifica textos. Solo colores + corazones vía CSS cuando theme_key = valentines_day.

insert into public.app_themes (
  theme_key,
  name,
  is_active,
  priority,
  primary_color,
  primary_dark_color,
  secondary_color,
  accent_color,
  background_color,
  surface_color,
  surface_soft_color,
  border_color,
  text_color,
  text_muted_color,
  card_radius,
  button_radius,
  logo_url,
  partner_logo_url,
  login_image_url,
  home_image_url,
  dashboard_image_url,
  home_background_url,
  home_background_mobile_url,
  home_monument_url,
  home_brand_word_url,
  home_partner_logo_url
) values (
  'valentines_day',
  'PHO3NIX Valentine''s',
  true,
  50,
  '#FF4F87',
  '#D81B60',
  '#FF6B6B',
  '#F7C6D9',
  '#080B16',
  '#171122',
  '#22152D',
  'rgba(255, 79, 135, 0.35)',
  '#FFFFFF',
  'rgba(255,255,255,0.70)',
  '24px',
  '16px',
  '/brand/pho3nix-logo.png',
  '/brand/lycan.png',
  '/themes/phoenix-guayaquil/images/home-guayaquil-wide-01.png',
  '/themes/phoenix-guayaquil/images/home-guayaquil-wide-01.png',
  '/themes/phoenix-guayaquil/images/home-guayaquil-wide-01.png',
  '/themes/phoenix-guayaquil/images/home-guayaquil-wide-01.png',
  '/themes/phoenix-guayaquil/images/home-guayaquil-vertical-01.png',
  '/themes/phoenix-guayaquil/guayaquil-monument.svg',
  '/themes/phoenix-guayaquil/phoenix-wordmark-bg.svg',
  '/brand/lycan.png'
)
on conflict (theme_key) do update set
  name = excluded.name,
  is_active = excluded.is_active,
  priority = excluded.priority,
  primary_color = excluded.primary_color,
  primary_dark_color = excluded.primary_dark_color,
  secondary_color = excluded.secondary_color,
  accent_color = excluded.accent_color,
  background_color = excluded.background_color,
  surface_color = excluded.surface_color,
  surface_soft_color = excluded.surface_soft_color,
  border_color = excluded.border_color,
  text_color = excluded.text_color,
  text_muted_color = excluded.text_muted_color,
  card_radius = excluded.card_radius,
  button_radius = excluded.button_radius,
  logo_url = excluded.logo_url,
  partner_logo_url = excluded.partner_logo_url,
  login_image_url = excluded.login_image_url,
  home_image_url = excluded.home_image_url,
  dashboard_image_url = excluded.dashboard_image_url,
  home_background_url = excluded.home_background_url,
  home_background_mobile_url = excluded.home_background_mobile_url,
  home_monument_url = excluded.home_monument_url,
  home_brand_word_url = excluded.home_brand_word_url,
  home_partner_logo_url = excluded.home_partner_logo_url;
